deny.toml
This was excluded by mistake in #1; without a configuration, cargo-deny
runs with a default one, and rejects a lot of things (largely due to
open-source-but-not-allowlisted licenses).
This `deny.toml` comes from the regalloc.rs repo. It results in one
warning currently that will be resolved once #7 is.
=> Add cargo-deny config.

doc/DESIGN.md, src/fuzzing/func.rs, src/ion/dump.rs, src/lib.rs
The documentation says that this is only used for heuristics, but it
is never actually called. This should be removed for now and perhaps
added back later if we find an actual use for it.
=> Remove Function::is_call

src/ion/process.rs, src/ion/requirement.rs
We never merge bundles from vregs of different classes, so we don't
need to check for register class conflicts.
=> Simplify Requirement by removing register classes

doc/DESIGN.md, src/lib.rs
The encoding for OperandConstraint is adjusted to free up 2 bits which
allows for 2^21 vregs and 2^6 pregs.
=> Adjust Operand encoding

src/checker.rs, src/fuzzing/func.rs, src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/mod.rs, src/ion/stackmap.rs, src/lib.rs
- Fixed a bug from #13 with PRegs with index > 32
- Removed `regs` from `MachineEnv` since it's not actually needed.
- Return safepoint_slots as Allocations instead of SpillSlots .
- This enables us to support reftype vregs in register locations in the
future.
-  Removed an unused `clobbers` vector.
=> Various fixes & minor improvements

src/checker.rs, src/ion/data_structures.rs, src/ion/process.rs
Changes in computation of bundle priorities during review of the initial
PR introduced a possible mis-ordering of priorities: inner-loop bundle
use weights could exceed the weights of 1_000_000 and 2_000_000 used for
minimal bundles without and with fixed uses (respectively). These two
kinds of minimal bundle are meant to be the highest-priority bundles,
evicting any other bundle they need to, because they can't be split
further. This PR introduces two special bundle weights for these two
kinds of bundles, and clamps all other bundle weights to just below
them.
Thanks to @Amanieu for reporting the issue! Fixes #19.
=> Fix fuzzbug related to bundle priority ordering.

src/cfg.rs, src/fuzzing/func.rs, src/ion/liveranges.rs, src/lib.rs, src/ssa.rs
Branch parameters are not proper operands, so it doesn't make sense to represent them using `Operand`s. The constraint is irrelevant (you always want `Any`), and so is the position within the instruction (early/late).
This PR adds `Function::branch_params` which returns the branch parameters directly as a list of `VReg`s.
This is also useful for rematerialization (#8): branch parameters don't need to be in an actual register or stack slot if we can rematerialize them later. This would normally be required by the `Any` constraint used for branch parameters.
=> Rework the API for outgoing blockparams

src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/moves.rs
When an instruction uses the same vreg constrained to multiple different
fixed registers, the allocator converts all but one of the fixed
constraints to `Any` and then records a special fixup move that copies
the value to the other fixed registers just before the instruction. This
allows the allocator to maintain the invariant that a value lives in
only one place at a time throughout most of its logic, and constrains
the complexity-fallout of this corner case to just a special last-minute
edit.
Unfortunately some recent CPU time thrown at the fuzzer has uncovered
a subtle interaction with the redundant move eliminator that confuses
the checker.
Specifically, when the correct value is *already* in the second
constrained fixed reg, because of an unrelated other move (e.g. because
of a …
=> Fix fuzzbug: add checker metadata for new vreg on multi-fixed-reg fixup move.

src/checker.rs, src/ion/moves.rs, src/ion/redundant_moves.rs, src/lib.rs
The symbolic checker currently works by tracking a single symbolic vreg label for each "alloc" (physical register or stack slot). On definition of a vreg into an alloc, the label is updated to the new vreg's name.
This worked quite well when the regalloc was simpler, but in the presence of redundant move elimination, it started to become apparent that the analysis has a shortcoming: when multiple vregs have the same value, and the regalloc has deduced this, it can make use of an alloc that is labeled with one vreg but use it as another vreg and the checker will not validate the use.
In other words, the regalloc became smart enough to avoid emitting unnecessary moves, but the checker was relying on those moves to know the most up-to-date symbolic name for a value in a physical location. In …
=> Rework checker to not require DefAlloc by tracking all vregs on each alloc.

src/fuzzing/func.rs, src/ion/data_structures.rs, src/ion/mod.rs, src/ion/moves.rs, src/lib.rs
If the client adds labels to vregs across ranges of instructions in the
input program, the regalloc will provide metadata in the `Output` that
describes the `Allocation`s in which each such vreg is stored for those
ranges. This allows the client to emit debug metadata telling a debugger
where to find program values at each point in the program.
This API surface had already been sketched, but no implementation
had existed (the returned debug-label info was always empty) prior
to this PR.
Developed as part of the regalloc2 integration in Cranelift. This is not
strictly needed by Cranelift -- currently it does a post-analysis to get
debug info -- but this will let us eliminate that post-analysis, and simplify
other aspects of the integration as well.
I've added debug-label generation to the …
=> Support for debug-labels.

src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/moves.rs, src/lib.rs
Previously, we kept a bool flag `is_pinned` in the `VRegData`, and we
required a `&[VReg]` of all pinned vregs to be provided by
`Function::pinned_vregs()`. This was (I think) done for convenience, but
it turns out not to really be necessary, as we can just query
`is_pinned_vreg` where needed (and in the likely implementation, e.g. in
Cranelift, this will be a `< NUM_PINNED_VREGS` check that can be
inlined). This adds convenience for the embedder (the main benefit), and
also reduces complexity, removes some state, and avoids some work
initializing the regalloc state for a run.
=> Simplify pinned-vreg API: don't require slice of all pinned vregs.

src/ion/liveranges.rs, src/lib.rs
Previously, the regalloc required all liveins to be defined by a
pseudoinstruction at the start of the function body. The regalloc.rs
compatibility shim did this, but it's slightly inconvenient when using
the API directly. This change allows pinned vregs to be implicit liveins
to the function body instead.
Developed during Cranelift integration (bytecodealliance/wasmtime#3942).
=> Allow pinned-vregs to be implicit liveins.

src/ion/liveranges.rs
The "reused input" operand constraint allows for an instruction to have
a def-operand whose allocation is constrained to reuse the same
allocation as one of the uses.
This is useful to express constraints needed for some instruction sets,
like x86, where at the ISA level, one register serves both as an input
and the output.
Unfortunately the way that we lower the constraints to liveranges does
not work if we have the same vreg used both for the reused input and
another input -- it results in impossible-to-solve constraints. For
example, the instruction
```
alu_op v42 use, v42 use, v43 def reuse(0)
```
would result in an impossible allocation.
This fixes liverange construction to properly handle all uses of the
vreg whose operand is reused, rather than just the one reused operand.
=> Allow for reused inputs when the reused vreg is also used as other (normal) uses.

src/ion/moves.rs, src/lib.rs
Previously, debug value-label support required each vreg to have a
disjoint sequence of instruction ranges, each with one label.
Unfortunately, it's entirely possible for multiple values at the program
level to map to one vreg at the IR level, leading to multiple labels.
This PR generalizes the debug-info generation support to allow for
arbitrary (label, range, vreg) tuples, as long as they are sorted by
vreg, with no other requirements. The lookup is a little more costly
when we generate the debuginfo, but in practice we shouldn't have more
than a *few* debug value labels per vreg, so in practice the constants
should be small.
=> Generalize debug-info support a bit.

src/ion/liveranges.rs, src/lib.rs
The `Operand` abstraction allows a def to be positioned at the "early"
point of an instruction, before its effect and alongside its normal
uses. This is intended to allow the embedder to express that a def may
be written before all uses are read, so it should not conflict with the
uses.
It's also convenient to use early defs to express temporaries, which
should be available throughout a regalloc-level instruction's emitted
sequence. In such a case, the register should not be used again after
the instruction, so it is dead following the instruction.
Strictly speaking, and according to regalloc2 prior to this PR, then the
temp will *only* conflict with the uses at the early-point, and not the
defs at the late-point (after the instruction), because it's dead past
its point of definition. But …
=> Early defs reserve a register for whole instruction.

src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/mod.rs, src/ion/moves.rs
This resolves an issue seen when the source program uses multiple
regclasses (Int and Float): in some cases, the logic that grabs the
vregs and retains them (with class) in `vreg_regs` missed a register and
we had a class mismatch. This occurred because data structures were
initialized assuming `Int` regclass at first.
This PR instead removes the `vreg_regs` array, stores the class
explicitly as an `Option<RegClass>` in the `VRegData`, and provides a
`Env::vreg()` method that reconstitutes a `VReg` given its index and its
observed class. We "observe" the class of every vreg seen during the
liveness pass (and we assert that every occurrence of the vreg index has
the same class). In this way, we still have a single source-of-truth for
the vreg class (the mention of the vreg itself) and we …
=> Record vreg classes explicitly during liverange pass.

src/ion/liveranges.rs, src/lib.rs
Currently, if this is done, overlapping liveranges are created, and we
hit an assert that ensures our non-overlapping and
built-in-reverse-order invariants during liverange construction.
One could argue that multiple defs of a single vreg don't make a ton of
sense -- which def's value is valid after the instruction? -- but if
they all get the same alloc, then the answer is "whatever was put in
that alloc", and this is just a case of an instruction being a bit
over-eager when listing its registers.
This can arise in practice when operand lists come from combinations or
concatenations: for example, in Cranelift's s390x backend, there is a
"Loop" pseudo-instruction, and the operands of the Loop are the operands
of all the sub-instructions.
It seems more logically cohesive overall to say that …
=> Make multiple defs of one vreg possible on one instruction.

.github/workflows/rust.yml, Cargo.toml, src/index.rs, src/ion/data_structures.rs, src/lib.rs
This adds derived `Serialize` and `Deserialize` implementations for
exposed types that describe registers, operands, and related program
inputs; entity indices; and regalloc output types. This allows
serialization of any of the embedder's IR data types that may embed or
build upon regalloc2 types.
These implementations (and the dependency on the `serde` crate itself)
are enabled only when the non-default `enable-serde` feature is
specified.
=> Add serde support for exposed types.

Cargo.toml
This will include #40 in a release to allow us to use it in Cranelift's bytecodealliance/wasmtime#3989.
=> Bump version to 0.1.1.

fuzz/fuzz_targets/ion_checker.rs, src/checker.rs, src/lib.rs
The checker was built to validate programs produced by the fuzzing
testcase generator, which was built before regalloc2 supported special
handling of moves. (In a pure-SSA world, move elision is not needed,
because moves are not needed, and blockparams are the only way of
tying together vregs.)
Due to this, the checker works great for our independent regalloc2
fuzzing setup, but when used on regalloc inputs produced by Cranelift,
cannot prove correctness.
This PR extends the checker's analysis to properly handle "program
moves", which are distinct from regalloc-inserted moves in that they
are present in the original program and hence are semantically
relevant. A program move edits all sets of symbolic vregs at all
allocs, and where the source vreg appears, it inserts the dest vreg as …
=> Support program moves, including pinned vregs, in the checker.

Cargo.toml
This will get #43 into a release to allow us to use the checker on
Cranelift outputs.
=> Bump version to 0.1.2.

src/ion/process.rs, src/ion/requirement.rs
Currently, we unconditionally trim the ends of liveranges around a split
when we do a split, including splits due to conflicts in a
liverange/bundle's requirements (e.g., a liverange with both a register
and a stack use). These trimmed ends, if they exist, go to the spill
bundle, and the spill bundle may receive a register during second-chance
allocation or otherwise will receive a stack slot.
This was previously measured to reduce contention significantly, because
it reduces the sizes of liveranges that participate in the first-chance
competition for allocations. When a split has to occur, we might as well
relegate the "connecting pieces" to a process that comes later, with a
hint to try to get the right register if possible but no hard connection
to either end.
However, in the case of a …
=> Handle conflict-related liverange splits arising from stack constraints without falling back to spill bundle.

Cargo.toml
Bumping version in order to release 0.1.3 with #49 included.
=> Bump to version 0.1.3.

fuzz/fuzz_targets/moves.rs, src/fuzzing/func.rs, src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/mod.rs, src/ion/moves.rs, src/lib.rs, src/moves.rs
Currently, regalloc2 sets aside one register per class, unconditionally,
to make move resolution possible. To solve the "parallel moves problem",
we sometimes need to conjure a cyclic permutation of data among
registers or stack slots (this can result, for example, from blockparam
flow that swaps two values on a loop backedge). This set-aside scratch
register is used when a cycle exists.
regalloc2 also uses the scratch register when needed to break down a
stack-to-stack move (which could happen due to blockparam moves on edges
when source and destination are both spilled) into a stack-to-reg move
followed by reg-to-stack, because most machines have loads and stores
but not memory-to-memory moves.
A set-aside register is certainly the simplest solution, but it is not
optimal: it means that …
=> Remove an explicitly-set-aside scratch register per class.

Cargo.toml
The change in #51 was API-visible (removal of the "scratch register"
field in the `Env`) so this is a semver bump.
=> Bump version to 0.2.0.

src/checker.rs, src/fuzzing/func.rs, src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/moves.rs, src/moves.rs
This fixes #53. Previously, if two operands on an instruction
specified *different* vregs constrained to the same physical register
at the Before (Early) and After (Late) points of the instruction, and
the Before was live downward as well, we would panic: we can't insert
a move into the middle of an instruction, so putting the first vreg in
the preg at Early implies we have an unsolveable conflict at Late.
We can solve this issue by adding some new logic to insert a copy, and
rewrite the constraint. This reuses the multi-fixed-reg-constraint
fixup logic. While that logic handles the case where the *same* vreg
has multiple *different* fixed-reg constraints, this new logic
handles *different* vregs with the *same* fixed-reg constraints, but
at different *program points*; so the two are …
=> Handle conflicting Before and After fixed-reg constraints with a copy.

src/ion/data_structures.rs, src/ion/spill.rs
The old logic, which did some linked-list rearranging to try to probe
more-likely-to-be-free slots first and which was inherited straight from
the original IonMonkey allocator, was slightly broken (error in
translation and not in IonMonkey, to be clear): it did not get the
list-splicing right, so quite often dropped a slot on the floor and
failed to consider it for further reuse.
On some experimentation, it seems to work just as well to keep a
SmallVec of spillslot indices per size class instead, and save the last
probe-point in order to spread load throughout the allocated slots while
limiting the number of probes (to bound quadratic behavior).
This change moves the maximum slot count from 285 to 92 in `python.wasm`
from bytecodealliance/wasmtime#4214, and the maximum frame size from …
=> Fix spillslot allocation to actually reuse spillslots.

src/ion/liveranges.rs
Right now, pinned vregs are a way of naming real registers (a
compatibility shim of sorts for Cranelift's `RealReg`s) and can be used
as sources and dests of moves. When the input program does so, regalloc2
converts these into "ghost" uses and defs on the other vreg of the move
(dest or source, respectively) with a fixed-register constraint. So
`move v128, v0` where `v0` is pinned to `p0` turns into a "ghost def"
on `v128` with constraint `fixed p0`.
There is some fancy manipulation of liveranges to make this all work
while properly recording where the preg's value must be preserved.
Unfortunately, there was an off-by-one in the location of the move and
transition of live-ranges which interacts poorly with the "implicit
live-in" of pinned vregs at function start. As a result, a function …
=> Bugfix: no hole in liveranges for pinned vreg move src.

Cargo.toml
This allows us to make a point-release of regalloc2 and consequently also of Cranelift to incorporate the fix in #60.
=> Version 0.2.3.

src/ion/mod.rs, src/ion/moves.rs, src/lib.rs
Two small changes related to logging, that try to simplify reasoning about how logs are enabled a bit:
- `annotate` already has a guard in the beginning of its body, checking if `annotations_enabled` is true. Most uses of this function aren't additionally guarded with `if log::log_enabled!(log::Level::Trace)`, so for consistency and since there's already the `enabled_annotations` guard, I've removed the extra `log_enabled` checks (in two places).
- `dump_state` uses the crate-defined `trace` macro that checks against the `trace-log` feature, but the check on top of `dump_state` uses the `log_enabled` check. Instead I've introduced another macro similar to `log::log_enabled` that follows the same logic as the crate-defined `trace` macro to decide whether to enter the block or not.
=> Streamline log enablement

src/cfg.rs, src/fuzzing/mod.rs, src/fuzzing/ssa.rs, src/lib.rs
The `vreg_def_blockparam` and `vreg_def_inst` fields on CFGInfo are only
used in `validate_ssa`, which in turn is only used in the ssagen fuzz
target.
Since these fields are never read in normal usage, initializing them is
entirely wasted effort. According to valgrind/DHAT, when running
`wasmtime compile` on the Sightglass Spidermonkey benchmark, removing
these fields saves about 100M instructions, 23k heap allocations
totalling 40MiB, and 47MiB of writes to the heap.
I tested the fuzz target for a few minutes, and also tested a release build of wasmtime. So I've built with the fuzzing feature both on and off, and there weren't any build warnings or errors in either case.
=> Only record vreg definitions when fuzzing

src/fuzzing/ssa.rs
This is an alternative to #67, based on things I learned while writing that.
I had trouble understanding `validate_ssa`, so this changes the division
of work to establish one invariant at a time:
- First, check that no VReg is defined in more than one place, and
record which block it's defined in.
- Second, check that each use refers to a VReg that was defined either
earlier in the same block, or in a block dominating it.
I'm also enhancing the validation to check that every VReg use is in an
instruction that is strictly later than its def. Previously, an earlier
operand in the same instruction would also be considered a valid def,
but that isn't actually legal in SSA.
=> validate_ssa: Check def uniqueness first

src/fuzzing/func.rs
Currently there is a loop that takes a variable step toward an end point
with an integer from `Arbitrary`; if this integer is always zero (for
example due to end-of-input?) then we add debug labels to a particular
input SSA value forever. This eventually causes an OOM crash.  This PR
bounds the loop at a reasonable count (10) instead.
=> Fuzzing function generator: bound the debug-labels size.

src/lib.rs
Also remove the previous workaround for const-assert now that it is available on stable Rust.
=> Make more `PReg` & `VReg` methods const

fuzz/fuzz_targets/ion_checker.rs, fuzz/fuzz_targets/ssagen.rs, src/checker.rs, src/fuzzing/func.rs, src/ion/liveranges.rs, src/lib.rs
This allows a non-allocatable `PReg` to be passed on directly to the allocations vector without any liverange tracking from the register allocator. The main intended use case is to support ISA-specific special registers such as a fixed zero register.
Fixes #3
=> Add fixed-non-allocatable operand support

fuzz/fuzz_targets/moves.rs, src/checker.rs, src/ion/moves.rs, src/lib.rs, src/moves.rs
Fixed stack slots are treated as `PReg`s by most of the register allocator, but need some additional handling the move resolver to avoid generating stack-to-stack moves.
=> Handle fixed stack slots in the move resolver

doc/DESIGN.md
Feel free to ignore! I was reading over the design doc and noticed a typo. After the first, I was hoping to find more so the PR wouldn't be so trivial, but alas I didn't find anything else.
=> Fix design doc typo

fuzz/fuzz_targets/moves.rs, src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/moves.rs, src/ion/spill.rs, src/lib.rs
The register allocator was already allowing moves between spillslots and registers of different classes, so this PR formalizes this by making spillslots independent of register class.
This also fixes #79 by properly tracking the register class of an `InsertedMove` with the `to_vreg` field which turns out to never be `None` in practice. Removing the `Option` allows the register class of the `VReg` to be used when building the per-class move lists.
Fixes #79
=> Remove register class from `SpillSlot`

src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/process.rs, src/ion/requirement.rs, src/ion/stackmap.rs
- Allow early-pos uses with fixed regs that conflict with clobbers (which happen at late-pos), in addition to the existing logic for conflicts with late-pos defs with fixed regs.
This is a pretty subtle issue that was uncovered in #53 for the def case, and the fix here is the mirror of that fix for clobbers. The root cause for all this complexity is that we can't split in the middle of an instruction (because there's no way to insert a move there!) so if a use is live-downward, we can't let it live in preg A at early-pos and preg B != A at late-pos; instead we need to rewrite the constraints and use a fixup move.
The earlier change to fix #53 was actually a bit too conservative in that it always applied when such conflicts existed, even if the downward arg was not live. This PR fixes that …
=> Some fixes to allow for call instructions to name args, returns, and clobbers with constraints.

Cargo.toml
This is identical to v0.3.3, but it turns out that the removal of the register class from `SpillSlot` (#80) is an API change. I missed this and published 0.3.3 but yanked it after it was causing build issues for folks.
=> Version 0.4.0.

src/ion/process.rs
When a liverange starts at a *late* point of an instruction, and it undergoes the fallback "split into all minimal pieces" transform, we end up creating one minimal bundle that starts at the *early* point of the instruction at the start of the original LR. This can create impossible-to-allocate situations where a fixed-constraint LR overlaps another constrained to the same register (e.g. at calls). We fix this by ensuring the minimal bundle is trimmed only to the half of the instruction that overlaps the original LR.
This is analogous to the third fix in #74, but on the other end (start of LR rather than end of it).
=> Fix fallback-split behavior: trim start of minimal bundle wrt start of original LR.

src/lib.rs
Clobbers don't conflict with early uses, so they effectively act as a late def, not an early def.
=> Fix documentation for `inst_clobbers`

src/ion/data_structures.rs, src/ion/mod.rs, src/ion/process.rs
Keep `conflict_set` allocated in `Env` instead of allocating a new one on every call. This improves register allocation performance by about 2%.
=> Cache `HashSet` in `try_to_allocate_bundle_to_reg`

README.md
=> Add README note that non-SSA support is deprecated.

Cargo.toml, src/ion/data_structures.rs
This PR updates the `UseList` type alias to a `SmallVec` with 4
`Use`s (which are 4 bytes each) rather than 2, because we get 16 bytes
of space "for free" in a `SmallVec` on a 64-bit machine.
This PR improves the compilation performance of Cranelift by 1% on
SpiderMonkey.wasm (measured on a Linux desktop with pinned CPU
frequency, and pinned to one core).
It's worth noting also that before making these changes, I explored
whether it would be possible to put the lists of uses and liveranges
in single large backing `Vec`s; the basic reason why we can't do this
is that during liverange construction, we append to many lists
concurrently. One could use a linked-list arrangement, and in fact RA2
did this early in its development; the separate `SmallVec`s were
better for performance overall …
=>  Modify a SmallVec inline size for UseList to be slightly larger.

src/indexset.rs, src/ion/data_structures.rs, src/ion/process.rs
According the Sightglass, these changes collectively are worth a 3% speedup by instructions retired, and 1-2% speedup by CPU cycles, when using Wasmtime to compile the bz2 and pulldown-cmark benchmarks. Hyperfine also reports a 2% speedup for each of the bz2, pulldown-cmark, and spidermonkey benchmarks.
=> Some small perf improvements

fuzz/fuzz_targets/moves.rs
Two fixes uncovered by a warning noted in #96:
- The iteration that was meant to be adding between 0 and 2 scratch registers was adding zero or one instead, because it was written as `for i in u.int_in_range(0..=2)` rather than `for i in 0..u.int_in_range(0..=2)?`. This is somewhat subtle but the `Result` is iterable so it was choosing zero if `u`'s input ended (making it unable to provide an arbitrary int) or one otherwise. This still would give some interesting fuzz coverage but was clearly not the original code's intent.
- Separately, it seems this fuzz target hadn't been run comprehensively in a while (we just run the toplevel `ion_checker` target on OSS-Fuzz, which checks the whole allocator; this target is meant to be a more focused way of testing the move resolver when hacking on …
=> Fix the `moves` fuzz target.

src/ion/data_structures.rs
We were using 2, which is the maximum for 32-bit architectures, but on 64-bit architectures we can get 4 inline elements without growing the size of the `SmallVec`.
This is a statistically significant speed up, but is so small that our formatting of floats truncates it (so less than 1%).
```
compilation :: instructions-retired :: benchmarks/bz2/benchmark.wasm
Δ = 3360297.85 ± 40136.18 (confidence = 99%)
more-inline-capacity.so is 1.00x to 1.00x faster than main.so!
[945563401 945906690.73 946043245] main.so
[942192473 942546392.88 942729104] more-inline-capacity.so
compilation :: instructions-retired :: benchmarks/pulldown-cmark/benchmark.wasm
Δ = 1780540.13 ± 39362.84 (confidence = 99%)
more-inline-capacity.so is 1.00x to 1.00x faster than main.so!
[1544990595 1545359408.41 1545626251] …
```
=> Use maximum inline capacity available for `SmallVec<VRegIndex>` in `SpillSet`

.github/workflows/rust.yml
Recent builds show deprecation warnings for `node12` coming from our use of the `checkout@v2` action. This PR bumps the uses of the checkout action to v3 to avoid the deprecation.
=> Bump the checkout action to v3 to avoid node12 deprecation

src/ssa.rs
- Don't check for defs on a use of a fixed-nonallocatable operand
- Add traces to the ssa validator to aid debugging
=> SSA Validator Fixes

src/checker.rs, src/indexset.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/moves.rs, src/lib.rs
This PR removes "pinned vregs" from regalloc2.
A pinned vreg is a vreg that is constrained to always be in a particular physical register at every operand that mentions it. (The value may be moved between its def/uses, but this should be transparent.)
Pinned vregs were built as a sort of compatibility feature for regalloc.rs' interface: that allocator allowed the embedder to mention physical registers directly in operands, and it would track liveranges on physical registers just like virtual registers.
In contrast, regalloc2 operands purely on vregs, and can track liveranges only on vregs. In order to emulate the above functionality, we set aside special vregs in order to stand in for the pregs' allocation state, and generated the implied constraints at every mention.
Pinned vregs were …
=> Remove pinned VRegs.

src/ion/liveranges.rs, src/ion/moves.rs, src/lib.rs, src/ssa.rs
(Stacked on top of #108; only the second commit is the real change here.)
This PR removes "mod" or "modify" operands. regalloc2 currently supports non-SSA input -- that is, code with multiple defs for the same register -- and as part of this support, a kind of operand that both uses the old value of a vreg and redefines it with a new value.
This operand kind was included for compatibility with regalloc.rs, because quite a few instructions in Cranelift used it to naturally describe the machine-level semantics. (For example, on x86, most ALU instructions modify one operand to replace it with the result.)
However, we've been pushing to refactor toward pure-SSA input, and thanks to @elliottt's work in Cranelift, non-SSA support is no longer needed in regalloc2. Instead, instructions now use …
=> Remove mod operands.

src/ion/moves.rs
In #108, we had removed a conditional that became constant-false with the removal of pinned vregs. Unfortunately, in a pretty embarrassing text-editing error, I removed the wrong end-brace and re-indented. This had the effect of moving some of the move-resolution code around in the regalloc backend, skipping moves in some cases and generating incorrect results.
Caught as a fuzzbug by OSS-Fuzz in [0] (public after this merges and is detected as fixed).
Fixes #110.
[0]: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55391
=> Fix indent/conditional removal in #108 that removed wrong brace.

Cargo.toml
Bump the version to 0.6.0 for the next publish to crates.io.
This version removes pinned registers and mod operands, which requires the bump to 0.6.0.
=> Bump to version 0.6.0

src/checker.rs
The checker works by keeping a worklist of blocks to process, and adds a block to the worklist when its entry state changes. Every entry state is initially `Top` (in a lattice). The entry block is explicitly added to the worklist to kick off the processing.
In ordinary cases, the entry block has some instructions that change state from `Top` to something else (lower in the lattice), and this is propagated to its successors; its successors are added to the worklist; and so on. No other state is `Top` from then on (because of monotonicity) so every reachable block is processed.
However, if the entry block is completely empty except for the terminating branch, the state remains `Top`; then the entry state of its successors, even when updated, is still `Top`; and the state didn't change so …
=> Fix checker when empty blocks result in unchanged-from-`Top` entry state.

src/checker.rs
This should have no functional change, just makes the source slightly easier to read and reason about.
Something I noticed while reviewing #113.
=> checker: Use a couple of Rust idioms

src/ion/liveranges.rs
A few refactorings I made while reading through the regalloc2 source. The diff looks larger than it is because of indent changes, so I'd recommend reviewing with space changes turned off.
- Use a while-let instead of checking is_empty and popping
- This conditional should always be true, as we expect the input is in ssa
- Use iter_mut instead of iterating the index
- We don't support multiple defs of the same vreg anymore
- Drain instead of clear
=> Misc refactorings

src/fuzzing/func.rs, src/ion/moves.rs, src/lib.rs
Dedicated scratch registers used for resolving move cycles were removed in #51 and replaced with an algorithm to automatically allocate a scratch register as needed.
However in many cases, a client will already have a non-allocatable scratch register available for things like extended jumps (see #91). It makes sense to re-use this register for regalloc than potentially spilling an existing register.
=> Re-introduce optional dedicated scratch registers

README.md, src/checker.rs, src/fuzzing/func.rs, src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/mod.rs, src/ion/moves.rs, src/lib.rs
This removes the last part of non-SSA support from regalloc2. Program moves allowed non-SSA code to copy a value from one vreg to another, but with SSA codegen this is not needed because the vreg itself can simply be reused directly.
Fixes #4
=> Remove support for program moves

src/ion/redundant_moves.rs
Iterate over the result of `Vec::drain` instead of iterating and then explicitly clearing the vector. Split out of #122 to minimize the diff.
=> Avoid using Vec::clear in clear_alloc

src/fuzzing/func.rs, src/ion/data_structures.rs, src/ion/mod.rs, src/ion/moves.rs, src/lib.rs
👋 Hey,
For machines with completely separate vector registers it is useful to have a separate third register class. It looks like we now have encoding space to support that.
I've run all 5 fuzzers for about a couple of hours, and nothing showed up.
Fixes: #47
=> Add a third register class

src/ion/liveranges.rs, src/lib.rs
This PR fixes 3 issues:
- `PReg::class` was broken by #126.
- `PRegSet` needs more than 128 bits for 3 register classes.
- `impl Display for Operand` was incorrect for fixed-non-allocatable operands.
=> Fix several bugs

src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/mod.rs, src/ion/moves.rs, src/ion/process.rs, src/ion/spill.rs, src/ion/stackmap.rs, src/moves.rs
This PR introduces overlapping live ranges in the handling of conflicting operand constraints, where previously we would handle these as a special case in `fixup_multi_fixed_vregs`.
There a few key changes needed to support overlapping live ranges:
* During move insertion, we need to buffer the previous liverange that we might consider moving from, as multiple liveranges could start at the current instruction. We also use this as an opportunity to try to keep the longest liverange around, preferring the longest source for each intra-block move.
* We no longer search for open stack slots by checking that all live ranges in a spill set would fit in the stack slot's occupied range, as the `LiveRangeKey` type treats all overlapping live ranges as equal. Instead we build a single code range …
=> Initial support for overlapping LiveRanges

src/ion/data_structures.rs, src/ion/mod.rs, src/ion/moves.rs
Instead of storing priority in each entry in `inserted_moves`, keep one vector for each priority level. This saves us four bytes per `inserted_moves` entry, and requires only that we sort on the program point of the moves, not the pair of program point and priority.
Profiling with both sightglass and hyperfine show that there is a very small improvement in compile time for benchmarks like `pulldown-cmark` and `bz2`, with larger benchmarks like `spidermonkey` showing the same performance. One downside is that the redundant move eliminator is less effective, as it's no longer working across priority levels. This comes up in the bz2 benchmark which sees a slight regression in runtime performance, due to excessive writes back to the stack of values that have spilled but are used in moves at …
=> Separate vectors for each priority level

src/ion/data_structures.rs, src/ion/mod.rs, src/ion/moves.rs
Reverts bytecodealliance/regalloc2#133
I'm noticing some fuzz bugs locally with this change applied, so I'd like to revert and investigate.
=> Revert "Separate vectors for each priority level"

src/ion/data_structures.rs, src/ion/mod.rs, src/ion/moves.rs
Move the vector of inserted moves out of the `Env` struct, and instead return it from `Env::apply_allocations_and_insert_moves`. `Env::resolve_inserted_moves` now consumes that vector directly, instead of mutating the `Env` state.
Additionally, we now skip recording moves where the source and dest allocations are the same.
This PR shows a small improvement in performance, with 1-2% improvements in compile time on bz2 and pulldown-cmark. There's some noise in the execution benchmarks, so I'm going to investigate the assembly diff to confirm that it's just noise.
```
compilation :: cycles :: benchmarks/bz2/benchmark.wasm                                                                         
Δ = 21747167.72 ± 7037094.92 (confidence = 99%) …
```
=> Refactor inserted move handling

src/ion/moves.rs
Use a hash map for block-param move sources instead of a vector, using the source block and destination block-param as the key. These two values uniquely define the source of the edge, as we require critical edges to have been split prior to running RA2.
This change in block-param source storage allows us to skip sorting the move source and destination data structures, and gives us the opportunity to apply a heuristic when multiple sources for a block-param move exist. Currently we prefer register sources, which is the same heuristic we apply for inter-block moves as well.
=> Prefer registers for block-param moves

src/ion/moves.rs
When a dedicated scratch register is provided by the environment, the redundant move eliminator needs to assume that this register can be clobbered by any instruction.
This register can't be specified as a clobber because it is also used by jump instructions which cannot have operands.
=> Handle dedicated scratch registers in the redundant move eliminator

src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs
This field was never written to after initialization, and the only function that looked at its value was never called.
=> Remove the merged_into field of LiveRangeData

src/ion/data_structures.rs, src/ion/mod.rs, src/ion/moves.rs
Return move edits from `resolve_inserted_moves` instead of eagerly allocating that vector in `Env`.
=> Move edits out of Env

Cargo.toml, deny.toml, regalloc2-tool/Cargo.toml, regalloc2-tool/src/main.rs, src/index.rs, src/lib.rs, src/serialize.rs
This PR has 2 components:
- A `SerializableFunction` which wraps a `Function` and `MachineEnv`. This type can be serialized and deserialized with Serde, and is enabled by the "enable-serde" feature.
- A `regalloc2-tool` binary which reads a bincode-encoded `SerializableFunction` and then runs the register allocator and checker on it.
This is a useful tool for debugging register allocation failures and to investigate cases of poor register allocation.
=> Add `regalloc2-tool`

src/ion/moves.rs
`get_reg` can be called multiple times if multiple scratch registers are needed (e.g. for stack-to-stack moves).
=> Fix handling of dedicated scratch registers

src/checker.rs
This was previously skipped: only Use operands were checked to ensure they had a valid allocation for their constraint.
No new fuzzbugs found, I just noticed this while looking over the checker.
=> Check constraints for Def operands in the checker

src/checker.rs, src/lib.rs
This significantly improves the performance of the checker when trace logging is not enabled.
=> Avoid generating the state in the check if logging is disabled

src/fuzzing/func.rs, src/ion/data_structures.rs, src/ion/merge.rs, src/ion/mod.rs, src/ion/spill.rs
This quickly triggers a fuzzbug when two classes have the same spillslot size. It turns out that this is caused by the parallel move resolver not supporting cross-class moves, which can happen if the parallel involves a spillslot used by different classes before/after the move.
=> Run the fuzzer with all register classes

Cargo.toml
This pulls in a fix for a stackslot confusion bug (among stack slots of the same size) from #152. The bug is reachable only if the embedder has the same stackslot size for different classes, and could result in sharing of a stackslot and thus moves between values of different class (which would likely cause panics in an embedder). This is reachable from RISC-V in Cranelift.
=> Version bump to 0.9.2.

src/ion/merge.rs
The previous check was overly conservative: we only need to reject bundles that have multiple uses in the same instruction.
This can only happen with an early use and a late def, so we round the start of each range containing a fixed def up to the start of its instruction to detect overlaps.
=> Allow merging bundles that have a fixed-reg def

fuzz/fuzz_targets/moves.rs, src/fuzzing/mod.rs, src/lib.rs
We want to also use this functionality in ABI glue in Cranelift.
I haven't tried using this module from Cranelift yet though. I'm mostly opening this PR as a quick check that there's nothing obviously wrong with just exposing the whole module.
=> Make parallel-moves resolver available publicly

src/moves.rs
I was trying to understand the public API of `ParallelMoves` by the method of reading the source, despite the presence of reasonable documentation I could have read instead, and I found some things about the implementation confusing. This PR makes it not confusing to me, which is hopefully a plus for others too?
One thing I'm not clear on: does anybody rely on the output move-list containing self-moves? If you tell the resolver that you want to move, say, `rdx` into `rdx`, the generated list of moves will have the same effects whether that self-move is included in the final list or not. But if the caller looks at the generated move list to pick a scratch register, for example, then removing the self-move could make the caller think that `rdx` is unused. Is that something to actually worry …
=> Simplify parallel-moves state machine

src/ion/merge.rs
Reverts bytecodealliance/regalloc2#155
Fuzzing discovered a case that caused the panic on line [1241 of src/ion/process.rs](https://github.com/bytecodealliance/regalloc2/blob/52bf322832b57b6103a06df6d4df5c6d59f1540a/src/ion/process.rs#L1241) to trigger.
=> Revert "Allow merging bundles that have a fixed-reg def"

src/moves.rs
Checking whether sources and dests overlap can use the same sort order that's needed later, as long as the check is updated to match.
I haven't done any benchmarking on this, but I have fuzzed it and didn't find any failures in 15 million inputs.
=> Only sort parallel-moves list once

src/ion/merge.rs
This was missed in #155, and previously wasn't an issue since such
bundles were never merged.
This PR also un-reverts #160, since the underlying bug is fixed.
=> Propagate the cached fixed-def flag when merging bundles

Cargo.toml
The current change set has been baking for a while, and it removes a lot of moves in the cranelift test suite.
=> Bump to version 0.9.3

src/fuzzing/func.rs, src/index.rs, src/ion/liveranges.rs, src/lib.rs
These are not needed except for one place in live range calculation where we can use a reversed iterator instead.
=> Remove support for backwards `InstRange`

src/fuzzing/func.rs, src/ion/liveranges.rs, src/lib.rs
These are useful to model fixed registers which should not be reused for other uses/defs. These were disallowed in #54, but this was too conservative.
Fundamentally, the only situation where a preg can be used in multiple fixed constraints within a single instruction is with an early-use and a late-def. Anything else is a user error because the live ranges will overlap.
As such this PR relaxes the operand rewrite from #54 to only apply in this specific situation. Fixed-late-use and fixed-early-def operands are left unchanged.
=> Allow fixed-early-def and fixed-late-use constraints

.github/workflows/rust.yml
I think we need at least version 0.13.9, which includes https://github.com/EmbarkStudios/cargo-deny/pull/513 to fix checking for yanked crates with the new sparse crates.io index format. I'm upgrading to the newest release just in case there's anything else we might want.
=> Upgrade cargo-deny to 0.14.22

fuzz/fuzz_targets/moves.rs, src/fuzzing/mod.rs, src/lib.rs
Reverts bytecodealliance/regalloc2#156
We never used this functionality in Cranelift. When we tried, we discovered that's it's pretty tricky to use correctly outside of the specific context it was written for in RA2, and then we found out that we didn't need it at all. So let's revert making it public.
=> Revert "Make parallel-moves resolver available publicly"

src/lib.rs
The changes will make it easier to increase the number of physical registers and register classes in the future.
=> Refactor PRegSet.

Cargo.toml
There have been a lot of changes since the 0.9.3 release, and it looks like they improve the quality of generated code in cranelift. Let's release 0.9.4!
=> Release version 0.9.4

doc/DESIGN.md, src/checker.rs, src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/process.rs, src/ion/requirement.rs, src/lib.rs
Following on from the removal of safepoints, remove the `OperandConstraint::Stack` and `Requirement::Stack` enum variants, as there's no longer any way to construct them.
Co-authored-by: Nick Fitzgerald <fitzgen@gmail.com>
=> Remove the OperandConstraint::Stack variant

Cargo.toml
Release version 0.10.0, which includes removing support for `InstRange::backwards` and support for generating safe points.
=> Bump to 0.10.0

Cargo.toml
As per #188, a new point-release that includes a version-bump of `rustc-hash` (and no other changes).
=> Version 0.10.1.

src/ion/data_structures.rs, src/ion/merge.rs
Fix a fuzzbug introduced in #185 where we missed updating a mask after also updating a constant indicating that the bit was no longer used. This PR fixes the bug by using the appropriate constant when masking, and also removing some additional functions that were missed in #185.
co-authored-by: Chris Fallin <chris@cfallin.org>
=> Fix bit packing of bundle params

doc/DESIGN.md, src/checker.rs
Stack maps are not provided by regalloc2 anymore. This removes the final references to stack maps in the codebase.
=> Remove some final references to stack maps

Cargo.toml
This includes two major updates:
- The new single-pass fast allocator (#181);
- An ability to reuse allocations across runs (#196).
=> Bump to version 0.11.0.

deny.toml, src/ion/merge.rs
While merging two bundles, the `merge_bundles` function appends two sorted vectors and sort the resulting vector again. This approach used to be fast in most cases, but rustc 1.81 introduced changes in sorting algorithm that made `sort_unstable_by_key` to behave very bad with vectors that are almost sorted.
This introduces an optimization consisting in handling the special case where the vector being appended contains a single item differently. This case is very common, and there's a benefit in handling it differently both with rust 1.81 and with earlier versions.
Fixes #203
=> Improve performance by optimizing  bundle merging logic.

Cargo.toml
Includes #204 to fix a performance regression with Rust 1.81's new standard library sort function.
=> Release 0.11.1.

src/ion/process.rs
In #196, various `break`s and early returns` out of a main allocator loop were changed to pass through a point that returned scratch storage to a context for later reuse.
Unfortunately, this refactor introduced a bug: a `break` became a `break 'outer`, and the latter meant that we were skipping some checks.
Fortunately this only happens in a code-path where the given allocation problem has too many constraints, and it means that we get a panic rather than a `TooManyLiveRegs` error cleanly returned, so this is not a security issue. However, it has me a little paranoid and we should carefully re-audit #196's changes when we get a chance.
(Discovered while making changes to ABI code that caused too many defs constrained to regs, resulting in an un-allocatable input; not reachable from …
=> TooManyLiveRegs check: fix `break` that was broken by allocator change.

src/ion/process.rs
When exerting additional pressure on regalloc with bytecodealliance/wasmtime#10502, which can lead to call instructions that have significantly more (`any`-constrained) defs, we hit panics in RA2 where (i) a bundle merged several LiveRanges, (ii) one of these LiveRanges had a fixed-reg constraint on an early use, (iii) this fixed-reg constraint conflicted with a clobber (which always happens at the late-point), (iv) the bundle merged in another LiveRange of some arbitrary def at the late point.
This would make a bundle (which is the atomic unit of allocation) that covers the whole inst, including the late point; and is required to be in the fixed reg; this is unallocatable because the clobber is also at the late point in that reg.
Our allocate-or-split-and-retry logic does not split if a …
=> Redefine a minimal bundle to have only one LiveRange.

fuzz/fuzz_targets/fastalloc_checker.rs, fuzz/fuzz_targets/ion_checker.rs, fuzz/fuzz_targets/ssagen.rs, src/fuzzing/func.rs
This is a followup from #214. We have use-cases in Cranelift now where we generate constraints on call instructions that have:
- A number of fixed-reg uses at "early";
- A number of fixed-reg defs at "late";
- A number of register clobbers, potentially overlapping with uses;
- A number of "any"-constrained defs at "late", to add register pressure.
The existing fuzzing function generator would create at most 3 operands, and would add *either* fixed-reg constraints *or* clobbers, not both.
This PR adds a "callsite-ish constraints" branch as a subcase of the fixed-reg choice that also adds the "any" defs to add register pressure, and adds new clobbers that don't interfere with existing constraints. It also loosens the logic around constructing fixed-reg constraints: if a conflict is found …
=> Fuzzing: add "callsite-ish constraints".

.gitignore, src/cfg.rs, src/checker.rs, src/fuzzing/func.rs, src/lib.rs, src/postorder.rs, src/ssa.rs
Hi, currently it is possible for two panics to happen when a function's SSA is being validated:
- If the block's numbering does not start at `0` or is non consecutive.
- If the vreg's numbering does not start at `0` or is non consecutive.
I ran into it after trying to use regalloc2's allocators in my toy/educational compiler project... I ended up with a hacked up clif file, something like:
```
test run
test compile
target x86_64
function %branch_diverge(i64, i64) -> i64 system_v {
block1(v0: i64, v1: i64):
brif v0, block2, block2
block2:
v6 = iconst.i64 1
v11 = iadd v6, v1
return v11
}
; run: %branch_diverge(0, 0) == 1
```
Which worked fine in my register allocator, as it uses hashmaps, but when trying to run regalloc2's allocators I got panics. Running `clif-util test` from cranelift …
=> Panics on non consecutive blocks and vregs ids

src/ion/mod.rs, src/ion/process.rs
This PR reworks minimal-bundle logic to be consistent between property computation and splitting, and overall simpler.
To recap: a "minimal bundle" is an allocation bundle that is as small as possible. Because RA2 does backtracking, i.e., can kick a bundle out of an allocation to make way for another, and because it can split, i.e. create more work for itself, we need to ensure the algorithm "bottoms out" somewhere to ensure termination. The way we do this is by defining a "minimal bundle": this is a bundle that cannot be split further. A minimal bundle is never evicted, and any allocatable input (set of uses/defs with constraints), when split into minimal bundles, should result in no conflicts. We thus want to define minimal bundles as *minimally* as possible so that we have the maximal …
=> Fix minimal-bundle splitting to avoid infinite loops.

src/lib.rs
This arose in #222. It has been the case for a while that we do not permit clobbers and defs to name the same physical register; this is because clobbers become defs internally. Unfortunately the doc-comment on the relevant part of the `Function` trait was out-of-date.
Ideally we would also detect this during validation or liverange construction rather than panic'ing later, but that is a separate concern (panic-cleanliness).
Note that this doesn't affect Cranelift; this is a concern mainly for docs correctness and for third-party users.
=> API documentation update: add a note about clobber/def conflicts.

src/checker.rs
The regalloc checker previously handled branches specially: it skipped the normal operand-procesing logic because it handles block-call arguments explicitly with parallel moves.
However, this is no longer fully correct in the presence of try-calls: these are branches but also have normal uses, defs, and clobbers, so we need to process those normally.
The comment noted also that we needed to skip operand processing on branches because edge-moves may come before branches, but I'm not sure that exemption ever made sense: if moves interfere with operands to the branch (e.g. conditional branch inputs) we should catch that too.
This simplifies the checker's instruction handling to no longer skip branches' operands, with no other changes (and no changes to the allocator itself).
Addresses …
=> Checker: process defs/clobbers on branches to allow checking of try-calls.

Cargo.toml
Includes #224 to fix a case where the checker had a false positive failure on branches with defs.
=> Release 0.12.1.

src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/mod.rs, src/lib.rs
This PR addresses an underlying limitation that became a problem for Cranelift recently, after folding return-value loads into call pseudoinsts (thus producing single instructions with many operands): we only supported 255 operands per instruction.
It appears that `Use` was using a `u8` for the "slot index" for an operand as a result of earlier optimization/packing efforts. However, the current shape of the struct leaves a padding byte free, so we should be able to expand to a `u16` with no loss in performance.
Furthermore, previously we weren't catching the overflow, but rather were silently wrapping around (eek). This properly returns a `RegAllocError::TooManyOperands` now if an instruction has too many operands (more than `u16::MAX`).
=> Handle up to 2^16 - 1 operands per inst, and error properly on more.

Cargo.toml
Includes fix from #226 for instructions with more than `u8::MAX` operands.
=> Release 0.12.2.

doc/ION.md, src/checker.rs, src/fastalloc/mod.rs, src/ion/data_structures.rs, src/ion/liveranges.rs, src/ion/merge.rs, src/ion/process.rs, src/ion/requirement.rs, src/lib.rs
In bytecodealliance/wasmtime#11285, we are discussing various approaches to allow generated code to communicate some "dynamic context" from exception-handling callsites to a stack-walker, without requiring changes to the overall frame format. The approach that seems to be the best choice so far is to add a stack-constrained vreg use to a try-call instruction and then communicate its location on the stack to the stack-walker in the exception metadata. The upshot of this is that we need support for stack-constrained operands.
Unfortunately we removed this support in #185 because we had removed the last (at the time) use-case for it, namely, GC stackmaps. Fortunately, reverting that PR (and most of a subsequent one, #192, that fixed up the removal), seems to be fairly straightforward. Those …
=> Re-add support for stack constraints.

doc/FASTALLOC.md, src/fastalloc/iter.rs, src/fastalloc/mod.rs, src/fastalloc/vregset.rs
Fixes https://github.com/bytecodealliance/regalloc2/issues/217.
- Adds support for an arbitrary number of Any def operands
- Adds support for stack-only operands
Benchmarking this branch against the implementation on the main branch with sightglass, most benchmarks have no significant difference while a few others have a speed difference of about 1-1.83x, with the main branch being faster on some and this branch being faster on others.
=> Arbitrary Any Defs and Stack-Only Constraints for Fastalloc

src/lib.rs
This is a non-functional change to refactor the base of several constants. When doing bitwise arithmetic, it is more clear to use `0b...` constants to visually see the bits. This project does this elsewhere; this change just updates several spots that did not.
=> Use bitfields for clarity in more places

src/ion/merge.rs
While queueing bundles, I noticed that we compute the priority of the bundle (i.e., the number of instructions) twice: once directly in `Env::queue_bundles` and again within
`Env::recompute_bundle_properties`. This change removes the first instance, saving some small amount of time iterating over the bundle's ranges.
=> Recompute priority only once during `init`

doc/FASTALLOC.md, src/fastalloc/iter.rs, src/fastalloc/lru.rs, src/fastalloc/mod.rs
Resolves https://github.com/bytecodealliance/wasmtime/issues/11545 and https://github.com/bytecodealliance/wasmtime/issues/11544.
- Add support for any, fixed-reg and stack-only branch arguments being defined in its branch instruction.
- Remove over-constraint on reservation of registers for operands with any-reg constraints. Instead, use counters to decide when it is safe to allocate registers to operands with no constraints.
- Correct `allocd_within_constraint` to account for allocation of clobbers to late phase registers.
- Correct `select_suitable_reg_in_lru` to only allocate available pregs in both late and early phases to early defs and late uses.
- Allocate late operands first, followed by early operands, instead of defs then uses.
- Remove over-constraint on available registers by …
=> Fastalloc Def branch arg on branch & Bug Fixes
