bytecodealliance/regalloc2

- src/checker.rs
- src/lib.rs
This adds a `block_insts_and_edits` function on `Output` which produces an iterator over the instructions and edits of a block after register allocation. It's a very useful helper function for any consumers of the regalloc output.
> Add a helper to iterate over insts and edits of a block in order

- src/checker.rs
This PR makes two changes, both suggested by @fitzgen in #36:
1. It updates the top-level description of the analysis to more
simply and accurately describe the analysis lattice.
2. It modifies both the `CheckerValue` and `CheckerState` types to be
enums with separate arms for the top/universe value, and adds helpers
as appropriate to update the values. There should be no functional
change; this update just makes the meet-functions and updates more
clear, and makes a bad state ("top" but with values) unrepresentable.
Closes #36.
> Make some improvements to clarity of checker implementation.

- Cargo.toml
This will allow us to pull in the fix in #54 in Cranelift.
> Bump version to 0.2.1.

- Cargo.toml
Making a point release in order to get #56 in a release.
> Version 0.2.2.

- Cargo.toml
Includes improvements in splitting performance (#59) and more efficient
handling of clobber lists (#58).
Semver break because of API change in #58.
> Release 0.3.0.

- Cargo.toml
This release includes the changes in #64.
> Release version 0.3.1.

- Cargo.toml
Includes a modest improvement in memory usage and performance by
removing analysis that was only used during fuzzing (#66).
> Version 0.3.2

- Cargo.toml
Includes fixes and enhancements from #74, #76, #77, #78, #80.
> Version 0.3.3.

- Cargo.toml
> Version 0.4.1.

- Cargo.toml
- src/ion/spill.rs
will make a release then update wasmtime
> Bump to version 0.4.2

- Cargo.toml
> Bump to 0.5.0

- Cargo.toml
Minor version bump to include a bug fix in the ssa validator.
> Bump to 0.5.1

- Cargo.toml
To be merged once #113 and #114 are in; I just want to queue up some CI here so everything is ready later.
> Bump version to 0.6.1.

- Cargo.toml
> Bump to version 0.8.0

- src/ion/process.rs
Simplify a loop slightly by using `core::mem::take` instead of iterating vector bounds and clearing.
> Use core::mem::take instead of clearing vectors

- Cargo.toml
This contains the bug fixes from #129.
> Bump version to 0.8.1

- src/ion/process.rs
Address https://github.com/bytecodealliance/wasmtime/issues/7147 by moving the bundle split point to the first fixed use found after the suggested split point. This implementation only considers the first liverange that contains the split point, so there's room for improvement.
The intent with this change is to not artificially constrain the bundle produced after the split point by leaving unconstrained uses that could be kept above the split point. Splitting at the first fixed use after the suggested split point should produce a less constrained upper bundle, which will be easier to allocate.
One interesting effect from the example in the issue linked above is that the change of split point alone does not fix the problem, as we also trim the space around the split point into the spill …
> Move the split point to the first fixed use

- Cargo.toml
Bump to version 0.10.2 to include the fix from #192.
> Update to 0.10.2

- Cargo.toml
> Release 0.11.2.

- Cargo.toml
> Version 0.11.3.

- Cargo.toml
> Release 0.13.0.
